// <auto-generated />
using System;
using HousePlanner.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HousePlanner.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructionMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RequiredQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("HouseDesignId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConstructionMaterials");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructionPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiEstimatedDurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PlannedDurationDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlannedStartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConstructionPhases");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructorProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ConstructorId", "Status");

                    b.HasIndex("ProjectId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Accepted'");

                    b.HasIndex("HouseDesignId", "ConstructorId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("ConstructorProjectRequests");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructorWorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<string>("Challenges")
                        .HasColumnType("text");

                    b.Property<string>("CompletedWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ConstructionPhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Issues")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TomorrowPlan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionPhaseId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConstructorWorkflowLogs");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.CostEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AppliedAreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("BudgetDeltaPercent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FormulaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LabourCostLkr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("MaterialCostLkr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("PricingSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TerrainType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalCostLkr")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("HouseDesignId")
                        .IsUnique()
                        .HasDatabaseName("IX_CostEstimates_HouseDesignId");

                    b.ToTable("CostEstimates");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.CostEstimationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AppliedAreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormulaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<int>("PricingRecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseDesignId");

                    b.HasIndex("WorkflowStateId", "StartedAt")
                        .HasDatabaseName("IX_CostEstimationRuns_Workflow_StartedAt");

                    b.ToTable("CostEstimationRuns");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.DailyConstructionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Challenges")
                        .HasColumnType("text");

                    b.Property<Guid?>("ConstructionPhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("MaterialsUsed")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProgressPercentage")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafetyIssues")
                        .HasColumnType("text");

                    b.Property<string>("TomorrowPlan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherCondition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WorkCompleted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkforceCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionPhaseId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("LogDate");

                    b.HasIndex("ProjectId");

                    b.ToTable("DailyConstructionLogs");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.HouseDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIVisualizationImage")
                        .HasColumnType("text");

                    b.Property<string>("AIVisualizationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("BasePreDesignedPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DesignSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FoundationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TechnicalPlanImage")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalBuiltUpAreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BasePreDesignedPlanId");

                    b.HasIndex("WorkflowStateId")
                        .HasDatabaseName("IX_HouseDesigns_WorkflowStateId");

                    b.HasIndex("WorkflowStateId", "IsArchived")
                        .HasDatabaseName("IX_HouseDesigns_WorkflowState_IsArchived");

                    b.HasIndex("WorkflowStateId", "IsCurrent")
                        .HasDatabaseName("IX_HouseDesigns_WorkflowState_IsCurrent");

                    b.HasIndex("WorkflowStateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_HouseDesigns_WorkflowState_Version");

                    b.ToTable("HouseDesigns");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.LandSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BasePreDesignedPlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BudgetLkr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LandPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LandSizeCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("LandSizePerches")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ManualTerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PlanSelectionMode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PreferredBathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredBedrooms")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredFloors")
                        .HasColumnType("integer");

                    b.Property<string>("StylePreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BasePreDesignedPlanId");

                    b.HasIndex("ClientId");

                    b.ToTable("LandSubmissions");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PreDesignedHousePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DesignCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("EstimatedConstructionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FloorCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMasterEnsuite")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOffice")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOpenPlan")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeparateDining")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUtilityRoom")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVeranda")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAccessibleFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("MinimumLandSizePerches")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinimumPlotLengthFt")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("MinimumPlotWidthFt")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SuitableTerrain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("TotalBuiltUpAreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Bathrooms");

                    b.HasIndex("Bedrooms");

                    b.HasIndex("DesignCode")
                        .IsUnique();

                    b.HasIndex("FloorCount");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Style");

                    b.HasIndex("SuitableTerrain");

                    b.ToTable("PreDesignedHousePlans");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalItemId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalItemName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OriginalUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QualityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitCostLkr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_PricingData_Provider_ExternalItemId");

                    b.HasIndex("Region", "QualityLevel")
                        .IsUnique()
                        .HasDatabaseName("UX_PricingData_Active_Labour_Region_Quality")
                        .HasFilter("\"IsActive\" = TRUE AND \"Category\" = 'labour'");

                    b.HasIndex("ItemName", "Region", "QualityLevel")
                        .IsUnique()
                        .HasDatabaseName("UX_PricingData_Active_Item_Region_Quality")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.ToTable("PricingData", null, t =>
                        {
                            t.HasCheckConstraint("CK_PricingData_Category", "\"Category\" IN ('material', 'labour')");

                            t.HasCheckConstraint("CK_PricingData_QualityLevel", "\"QualityLevel\" IN ('Basic', 'Standard', 'Premium', 'Luxury')");
                        });
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("NewValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PricingDataId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PricingDataId", "ChangedAt");

                    b.ToTable("PricingHistory");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingImportAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_PricingImportAudits_StartedAt");

                    b.ToTable("PricingImportAudits");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiEstimatedTotalDurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ContractorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlannedTotalDurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.HasIndex("HouseDesignId");

                    b.HasIndex("WorkflowStateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSqft")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("WallHeight")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("HouseDesignId")
                        .HasDatabaseName("IX_Rooms_HouseDesignId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("SupabaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SupabaseUid")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_SupabaseUid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ValidationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchitectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchitectReview")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectId");

                    b.HasIndex("ClientId");

                    b.HasIndex("HouseDesignId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_ValidationRequests_Status_CreatedAt");

                    b.HasIndex("WorkflowStateId", "HouseDesignId", "Status")
                        .HasDatabaseName("IX_ValidationRequests_Workflow_Design_Status");

                    b.ToTable("ValidationRequests");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.WorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentExecutionLogJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ToolAuditLogJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstructionPlan")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LandSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotableFeatures")
                        .HasColumnType("jsonb");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PreferredHouseDesignId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlopeEstimate")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TerrainType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("LandSubmissionId");

                    b.HasIndex("PreferredHouseDesignId")
                        .HasDatabaseName("IX_WorkflowStates_PreferredHouseDesignId");

                    b.ToTable("WorkflowStates");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructionMaterial", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany()
                        .HasForeignKey("HouseDesignId");

                    b.HasOne("HousePlanner.API.Entities.ConstructionPhase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId");

                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("HouseDesign");

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructionPhase", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany("ConstructionPhases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructorProjectRequest", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany()
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("Customer");

                    b.Navigation("HouseDesign");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ConstructorWorkflowLog", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.ConstructionPhase", "ConstructionPhase")
                        .WithMany()
                        .HasForeignKey("ConstructionPhaseId");

                    b.HasOne("HousePlanner.API.Entities.User", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionPhase");

                    b.Navigation("Constructor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.CostEstimate", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany("CostEstimates")
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseDesign");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.CostEstimationRun", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany()
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseDesign");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.DailyConstructionLog", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.ConstructionPhase", "ConstructionPhase")
                        .WithMany()
                        .HasForeignKey("ConstructionPhaseId");

                    b.HasOne("HousePlanner.API.Entities.User", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionPhase");

                    b.Navigation("Constructor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.HouseDesign", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.PreDesignedHousePlan", "BasePreDesignedPlan")
                        .WithMany("DerivedDesigns")
                        .HasForeignKey("BasePreDesignedPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany("HouseDesigns")
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasePreDesignedPlan");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.LandSubmission", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.PreDesignedHousePlan", "BasePreDesignedPlan")
                        .WithMany()
                        .HasForeignKey("BasePreDesignedPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HousePlanner.API.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasePreDesignedPlan");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingData", b =>
                {
                    b.OwnsOne("HousePlanner.API.Entities.TerrainMultiplierData", "TerrainMultiplier", b1 =>
                        {
                            b1.Property<int>("PricingDataId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Coastal")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "coastal");

                            b1.Property<decimal>("Flat")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "flat");

                            b1.Property<decimal>("Hillside")
                                .HasColumnType("numeric")
                                .HasAnnotation("Relational:JsonPropertyName", "hillside");

                            b1.HasKey("PricingDataId");

                            b1.ToTable("PricingData");

                            b1.ToJson("TerrainMultiplier");

                            b1.WithOwner()
                                .HasForeignKey("PricingDataId");
                        });

                    b.Navigation("TerrainMultiplier")
                        .IsRequired();
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingHistory", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.PricingData", "PricingData")
                        .WithMany("History")
                        .HasForeignKey("PricingDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PricingData");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Project", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId");

                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany()
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("HouseDesign");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Room", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany("Rooms")
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseDesign");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.User", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.ValidationRequest", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "Architect")
                        .WithMany()
                        .HasForeignKey("ArchitectId");

                    b.HasOne("HousePlanner.API.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.HouseDesign", "HouseDesign")
                        .WithMany()
                        .HasForeignKey("HouseDesignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HousePlanner.API.Entities.WorkflowState", "WorkflowState")
                        .WithMany()
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architect");

                    b.Navigation("Client");

                    b.Navigation("HouseDesign");

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.WorkflowState", b =>
                {
                    b.HasOne("HousePlanner.API.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("HousePlanner.API.Entities.LandSubmission", "LandSubmission")
                        .WithMany()
                        .HasForeignKey("LandSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousePlanner.API.Entities.HouseDesign", null)
                        .WithMany()
                        .HasForeignKey("PreferredHouseDesignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("LandSubmission");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.HouseDesign", b =>
                {
                    b.Navigation("CostEstimates");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PreDesignedHousePlan", b =>
                {
                    b.Navigation("DerivedDesigns");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.PricingData", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.Project", b =>
                {
                    b.Navigation("ConstructionPhases");
                });

            modelBuilder.Entity("HousePlanner.API.Entities.WorkflowState", b =>
                {
                    b.Navigation("HouseDesigns");
                });
#pragma warning restore 612, 618
        }
    }
}
